### ISSUE TITLE
You have wrong links in marketplace to your repository

### ISSUE THREAD

**Issue by kanlukasz** [gurumukhi/vscode-extension-line-count#2]
![obraz](https://user-images.githubusercontent.com/30685349/73381712-7f9a5500-42c6-11ea-84a6-6ef2db918106.png)

**Comment by gurumukhi** [comment]
Thanks for reporting, the issue is now fixed (https://marketplace.visualstudio.com/items?itemName=gurumukhi.selected-lines-count).
